/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutSessionRouteImport } from './routes/workout-session'
import { Route as TestInicialRouteImport } from './routes/test-inicial'
import { Route as PlanSemanalRouteImport } from './routes/plan-semanal'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutSessionRoute = WorkoutSessionRouteImport.update({
  id: '/workout-session',
  path: '/workout-session',
  getParentRoute: () => rootRouteImport,
} as any)
const TestInicialRoute = TestInicialRouteImport.update({
  id: '/test-inicial',
  path: '/test-inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSemanalRoute = PlanSemanalRouteImport.update({
  id: '/plan-semanal',
  path: '/plan-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/test-inicial': typeof TestInicialRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/test-inicial': typeof TestInicialRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/test-inicial': typeof TestInicialRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/perfil'
    | '/plan-semanal'
    | '/test-inicial'
    | '/workout-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/perfil'
    | '/plan-semanal'
    | '/test-inicial'
    | '/workout-session'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/perfil'
    | '/plan-semanal'
    | '/test-inicial'
    | '/workout-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PlanSemanalRoute: typeof PlanSemanalRoute
  TestInicialRoute: typeof TestInicialRoute
  WorkoutSessionRoute: typeof WorkoutSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-session': {
      id: '/workout-session'
      path: '/workout-session'
      fullPath: '/workout-session'
      preLoaderRoute: typeof WorkoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-inicial': {
      id: '/test-inicial'
      path: '/test-inicial'
      fullPath: '/test-inicial'
      preLoaderRoute: typeof TestInicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-semanal': {
      id: '/plan-semanal'
      path: '/plan-semanal'
      fullPath: '/plan-semanal'
      preLoaderRoute: typeof PlanSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PlanSemanalRoute: PlanSemanalRoute,
  TestInicialRoute: TestInicialRoute,
  WorkoutSessionRoute: WorkoutSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
