/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutSessionRouteImport } from './routes/workout-session'
import { Route as PlanSemanalRouteImport } from './routes/plan-semanal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutSessionRoute = WorkoutSessionRouteImport.update({
  id: '/workout-session',
  path: '/workout-session',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSemanalRoute = PlanSemanalRouteImport.update({
  id: '/plan-semanal',
  path: '/plan-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/workout-session': typeof WorkoutSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/plan-semanal'
    | '/workout-session'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/onboarding' | '/plan-semanal' | '/workout-session'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/plan-semanal'
    | '/workout-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanSemanalRoute: typeof PlanSemanalRoute
  WorkoutSessionRoute: typeof WorkoutSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-session': {
      id: '/workout-session'
      path: '/workout-session'
      fullPath: '/workout-session'
      preLoaderRoute: typeof WorkoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-semanal': {
      id: '/plan-semanal'
      path: '/plan-semanal'
      fullPath: '/plan-semanal'
      preLoaderRoute: typeof PlanSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PlanSemanalRoute: PlanSemanalRoute,
  WorkoutSessionRoute: WorkoutSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
